In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import time

data = pd.read_csv('/content/sample_data/Science1Lakh.csv')
data.head()

#LABEL ENCODING CONVERT CATEGORICAL DATA TO NUMERICAL DATA
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
data['TEAM-WORK']=l1.fit_transform(data['TEAM-WORK'])
data['INTEREST']=l1.fit_transform(data['INTEREST'])
data['COMPETIVE-EXAM-WINNER']=l1.fit_transform(data['COMPETIVE-EXAM-WINNER'])
data['LEADERSHIP-SKILL']=l1.fit_transform(data['LEADERSHIP-SKILL'])
data['WORK-LIFE-BALANCE']=l1.fit_transform(data['WORK-LIFE-BALANCE'])
data['CERTIFICATIONS']=l1.fit_transform(data['CERTIFICATIONS'])
data['SELF-LEARNING-CAPABILITY']=l1.fit_transform(data['SELF-LEARNING-CAPABILITY'])


#CONVERT SUBJECT GRADES TO  NUMBER 
grade={"PHYSICS":{"D":45,"C":60,"B":70,"B+":75,"A":85,"A ":85,"A+":90},
       "CHEMISTRY":{"D":45,"C":60,"B":70,"B+":75,"A":85,"A ":85,"A+":90},
       "MATHS":{"D":45,"C":60,"B":70,"B+":75,"A":85,"A ":85,"A+":90},
       "BIOLOGY":{"D":45,"C":60,"B":70,"B+":75,"A":85,"A ":85,"A+":90},
       "COMPUTER":{"D":45,"C":60,"B":70,"B+":75,"A":85,"A ":85,"A+":90},
       "LANGUAGE":{"D":45,"C":60,"B":70,"B+":75,"A":85,"A ":85,"A+":90},
       "SOCIO-ECONOMIC-FACTORS":{"PERSONAL-PREFERENCE":1,"JOB-SECURITY":2,"ECONOMIC-STATUS":3,"OTHERS":4},
       "M-SCORE":{"HIGH":90,"MEDIUM":70,"LOW":50}
      }
data=data.replace(grade)
print("\n\n")

#TRAIN-TEST SPLIT
X=data.drop(['CAREER'], axis = 1) #FEATURES
Y=data['CAREER'] #OUTPUT LABELS
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

#FEATURE SCALING
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

# KNN Algorithm
print("***********************KNN***************************\n")
import time
start=time.time()
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors = 4) 
knn.fit(X_train, Y_train) 
Y_pred = knn.predict(X_test) 
end=time.time()
print("Time=",end-start)
print("Predicted Value :")
print(Y_pred)

#CONFUSION MATRIX USED FOR MODEL EVALUATION   
print("\nConfusion Matrix : model evaluation")
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_test, Y_pred))
    
print("\n Classification report :")
from sklearn.metrics import classification_report
print(classification_report(Y_test, Y_pred))

#MODEL ACCURACY    
print("\nKNN Accuracy: ")
from sklearn import metrics
print((metrics.accuracy_score(Y_test, Y_pred))*100)


#NAIVE-BAYES
print("*****************NAIVE-BAYES*******************\n")
import time
Start = time.time ()
from sklearn.naive_bayes import GaussianNB 
naive_bayes = GaussianNB() 
naive_bayes.fit(X_train, Y_train) 
Y_pred = naive_bayes.predict(X_test) 
print("Predicted Value :")
print(Y_pred)
    
print("\nConfusion Matrix : model evaluation")
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_test, Y_pred))
    
print("\n Classification report :")
from sklearn.metrics import classification_report
print(classification_report(Y_test, Y_pred))
    
print("\nNaive-Bayes Accuracy : ")
from sklearn import metrics
print((metrics.accuracy_score(Y_test, Y_pred))*100)
a1=(metrics.accuracy_score(Y_test, Y_pred))*100
end= time.time()
b1 = str(round(end-Start,2))
print(b1)

#DECISION TREE
print("******************DECISION TREE***********************\n")
import time
Start = time.time ()
from sklearn.tree import DecisionTreeClassifier 
Decision_tree= DecisionTreeClassifier(criterion = 'gini') 
Decision_tree.fit(X_train, Y_train)
Y_pred = Decision_tree.predict(X_test) 
print("Predicted Value :")
print(Y_pred)
    
print("\nConfusion Matrix : model evaluation")
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_test, Y_pred))
    
print("\n Classification report :")
from sklearn.metrics import classification_report
print(classification_report(Y_test, Y_pred))
    
print("\nDecision Tree Accuracy : ")
from sklearn import metrics
print((metrics.accuracy_score(Y_test, Y_pred))*100)
a2=(metrics.accuracy_score(Y_test, Y_pred))*100
end= time.time()
b2=str(round(end-Start,2))
print(b2)

print("\n\n")

#LOGISTIC-REGRESSION
print("*****************LOGISTIC-REGRESSION*********************\n")
import time
Start = time.time ()
from sklearn.linear_model import LogisticRegression 
logistic = LogisticRegression(max_iter=9000) 
logistic.fit(X_train, Y_train)
Y_pred = logistic.predict(X_test) 
print("Predicted Value :")
print(Y_pred)
    
print("\nConfusion Matrix : model evaluation")
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_test, Y_pred))
    
print("\n Classification report :")
from sklearn.metrics import classification_report
print(classification_report(Y_test, Y_pred))
    
print("\nLogistic Regression Accuracy : ")
from sklearn import metrics
print((metrics.accuracy_score(Y_test, Y_pred))*100)
a3=(metrics.accuracy_score(Y_test, Y_pred))*100
end= time.time()
b3=str(round(end-Start,2))
print(b3)
print("\n\n")

#Adaboost Classifier
import time
start=time.time()
from sklearn.ensemble import AdaBoostClassifier
abc = AdaBoostClassifier()
# Train Adaboost Classifer
model = abc.fit(X_train, Y_train)
Y_pred = model.predict(X_test)
print("Adaboost-ACCURACY => "+str(metrics.accuracy_score(Y_test, Y_pred)*100)+str(" %"))
end=time.time()
print("time="+str(end-start))
#CLASSIFICATION REPORT
from sklearn.metrics import classification_report,confusion_matrix
#CONFUSION MATRIX
print(confusion_matrix(Y_test,Y_pred))
print('\n')
print(classification_report(Y_test,Y_pred))

#two hidden layers - MLP
import time
start=time.time()
from sklearn.neural_network import MLPClassifier
mlp= MLPClassifier(hidden_layer_sizes=(8,8), activation='relu', solver='adam',max_iter=200)
mlp.fit(X_train,Y_train)
Y_pred=(mlp.predict(X_test))
print("MLP-ACCURACY => "+str(metrics.accuracy_score(Y_test, Y_pred)*100)+str(" %"))
end=time.time()
print("time="+str(end-start))
#CLASSIFICATION REPORT
from sklearn.metrics import classification_report,confusion_matrix
#CONFUSION MATRIX
print(confusion_matrix(Y_test,Y_pred))
print('\n')
print(classification_report(Y_test,Y_pred))

#ANN
#FEATURE SCALING
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
print(X_train)

print("\nONE-HOT-ENCODING")
#one-hot-encoding to convert multiclass values 
print(Y_train)
from keras.utils import to_categorical
Y_train= to_categorical(Y_train)
Y_test= to_categorical(Y_test)
print(Y_train)

#BUILDING ANN
import tensorflow as tf
ann=tf.keras.models.Sequential()
#Add input layer
ann.add(tf.keras.layers.Dense(units=10,activation='relu'))
#Add 3 hidden Layers
ann.add(tf.keras.layers.Dense(units=10,activation='relu'))
ann.add(tf.keras.layers.Dense(units=10,activation='relu'))
ann.add(tf.keras.layers.Dense(units=10,activation='relu'))
#output layer
ann.add(tf.keras.layers.Dense(units=4,activation='softmax'))

#TRAIN ANN
ann.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
ann.fit(X_train,Y_train,batch_size=32,epochs=20)









***********************KNN***************************

Time= 78.36897945404053
Predicted Value :
[2 1 1 ... 1 2 1]

Confusion Matrix : model evaluation
[[4404 1089  745]
 [1636 5258  845]
 [1302 1332 3389]]

 Classification report :
              precision    recall  f1-score   support

           1       0.60      0.71      0.65      6238
           2       0.68      0.68      0.68      7739
           3       0.68      0.56      0.62      6023

    accuracy                           0.65     20000
   macro avg       0.66      0.65      0.65     20000
weighted avg       0.66      0.65      0.65     20000


KNN Accuracy: 
65.255
*****************NAIVE-BAYES*******************

Predicted Value :
[3 1 1 ... 2 3 1]

Confusion Matrix : model evaluation
[[1961 2595 1682]
 [1337 4584 1818]
 [ 974 2414 2635]]

 Classification report :
              precision    recall  f1-score   support

           1       0.46      0.31      0.37      6238
           2       0.48      0.59      0.53     

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLP-ACCURACY => 60.49 %
time=47.2858669757843
[[3452 1774 1012]
 [1180 5169 1390]
 [ 839 1707 3477]]


              precision    recall  f1-score   support

           1       0.63      0.55      0.59      6238
           2       0.60      0.67      0.63      7739
           3       0.59      0.58      0.58      6023

    accuracy                           0.60     20000
   macro avg       0.61      0.60      0.60     20000
weighted avg       0.61      0.60      0.60     20000

[[ 0.04900114 -1.75934165 -0.67635584 ...  0.88422636  0.90624847
   0.631833  ]
 [ 0.32207832 -0.11064796 -0.67635584 ... -1.13093213 -1.10345014
   0.631833  ]
 [ 0.59515549  1.53804574 -0.11093548 ...  0.88422636  0.90624847
   0.631833  ]
 ...
 [-0.01926815 -0.11064796  1.58532563 ...  0.88422636  0.90624847
  -1.58269669]
 [-0.56542251 -0.66021252  1.01990526 ... -1.13093213 -1.10345014
   0.631833  ]
 [ 0.39034761  0.98848118 -0.67635584 ...  0.88422636  0.90624847
   0.631833  ]]

ONE-HOT-ENCODING
34555 